### ISSUE TITLE
Discussion: create pull request and issues

### ISSUE THREAD

**Issue by catgoose** [Willem-J-an/adopure.nvim#3]
I'd be willing to work on this, but I wanted to see if there is any plans to add support to create PR/issues?

**Comment by Willem-J-an** [comment]
Create PR yes, issues no. Would like to keep it focused on a smooth PR experience rather than simply covering all functionality without actually improving the experience 😁

**Comment by catgoose** [comment]
That makes sense.  When I get some time I may take a look and submit a PR.
