### ISSUE TITLE
error loading module adopure.api

### ISSUE THREAD

**Issue by NeelSinha** [Willem-J-an/adopure.nvim#4]
Error executing Lua callback: ...al/share/nvim/plugged/adopure.nvim/lua/adopure/state.lua:85: loop or previous error loading module 'adopure.api'
stack traceback:
        [C]: in function 'require'
        ...al/share/nvim/plugged/adopure.nvim/lua/adopure/state.lua:85: in function 'new'
        ...a/.local/share/nvim/plugged/adopure.nvim/lua/adopure.lua:185: in function 'load_state_manager'
        ...a/.local/share/nvim/plugged/adopure.nvim/lua/adopure.lua:100: in function <...a/.local/share/nvim/plugged/adopure.nvim/lua/adopure.lua:99>
        ...a/.local/share/nvim/plugged/adopure.nvim/lua/adopure.lua:85: in function 'execute_or_prompt'
        ...a/.local/share/nvim/plugged/adopure.nvim/lua/adopure.lua:107: in function 'impl'
        ...a/.local/share/nvim/plugged/adopure.nvim/lua/adopure.lua:172: in function 'ado_pure'
        ...a/.local/share/nvim/plugged/adopure.nvim/plugin/init.lua:2: in function <...a/.local/share/nvim/plugged/adopure.nvim/plugin/init.lua:1>
        
       
       
       after adding pat token

**Comment by Willem-J-an** [comment]
Can you show me your code, what are you doing when this happens?
