### ISSUE TITLE
seems unable to extract git details 

### ISSUE THREAD

**Issue by konstantin-mohin** [Willem-J-an/adopure.nvim#7]
token is added, 

`Error executing Lua callback: .../.local/share/nvim/lazy/adopure.nvim/lua/adopure/git.lua:43: invalid value (nil) at index 2 in table for 'concat'
stack traceback:
        [C]: in function 'concat'`

**Comment by Willem-J-an** [comment]
What is your output for
```bash
git remote -v
```
Feel free to obfuscate any names you don't want to share.

**Comment by konstantin-mohin** [comment]
origin	org-name@vs-ssh.visualstudio.com:v3/org/ZoomInCloud/ZoomInCloud (fetch)
origin	org-name@vs-ssh.visualstudio.com:v3/org/ZoomInCloud/ZoomInCloud (push)

**Comment by Willem-J-an** [comment]
This seems to be the legacy ssh remote URL which is currently not supported by the plugin. https://learn.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops

Would you be able to update these urls to the new format? I'm currently unable to make the changes to add support for this to the plugin. Feel free to create a PR if you want to take a crack at it.

**Comment by konstantin-mohin** [comment]
thanks for checking, yeah will try to migrate to new format.
